config/routes.rb
Rails.application.routes.draw do


  root to: 'choices#index'
  get '/Brazil' , to: 'brazil#index'
  get '/Cambodian' , to: 'cambodian#index'
  get '/Indian' , to: 'indian#index'
  get '/Malaysian' , to: 'malaysian#index'
  get '/MalaysianPlus' , to: 'malaysianplus#index'

  resources :products, only: [:index, :show]

  resource :cart, only: [:show], controller: :cart do
    resources :items, only: [:create]
    resource :payment, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :items, class_name: :OrderItem

  def self.for_session(session)
    if session[:cart_id]
      Order.find(session[:cart_id])
    else
      Order.create
    end
  end

  def total
    items.inject(0) { |total, item| total + item.subtotal }
  end

  def purchased?
    purchased_at.present?
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  def subtotal
    product.unit_price * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/brazil_controller.rb
class BrazilController < ApplicationController
  def index
    @products = Product.all
  end
end

app/controllers/cambodian_controller.rb
class CambodianController < ApplicationController
  def index
    @products = Product.all
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    order = Order.for_session(session)
    presenter = OrderPresenter.new(order)

    respond_to do |format|
      format.html
      format.json { render json: presenter }
    end
  end
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
  def index
    @products = Product.all
  end
end

app/controllers/indian_controller.rb
class IndianController < ApplicationController
  def index
    @products = Product.all

  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    order = Order.for_session(session)
    session[:cart_id] = order.id

    AddToCart.call(order, item_params)

    presenter = OrderPresenter.new(order)
    render json: presenter
  end

  private

  def item_params
    params.require(:item).permit(:quantity, :product_id)
  end
end

app/controllers/malaysian_controller.rb
class MalaysianController < ApplicationController
  def index
    @products = Product.all

  end
end

app/controllers/malaysianplus_controller.rb
class MalaysianplusController < ApplicationController
  def index
    @products = Product.all

  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def create
    token = params[:card_token]
    cart = Order.find(session[:cart_id])

    charge = Stripe::Charge.create(
      amount: 1000,
      currency: 'aud',
      description: 'buying stuff',
      source: token
    )

    render json: charge
  rescue Stripe::CardError => e
    render json: { paid: false, error: e.message }, status: 402
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/brazil/index.html.erb
<% @products.each do |product| %>
  <% if product.category == "Brazil" %>
        <section class="section">
              <div class="box">
                <article class="product media">
                  <figure class="media-left">
                    <p class="image is-128x128">
                      <img src="http://placehold.it/256x256">
                    </p>
                  </figure>
                  <div class="media-content">
                    <div class="content">
                      <p>
                        <strong><%= product.name %></strong>
                      </p>
                    </div>
                    <nav class="level">
                      <div class="level-left">
                        <a href="#" data-product-id="<%= product.id %>" class="add-to-cart level-item">
                          <span class="icon"><i class="fa fa-cart-plus"></i></span>
                          Add to Cart
                        </a>
                      </div>
                    </nav>
                  </div>
                </article>
              </div>
        </section>

    <% end %>
<% end %>

app/views/cambodian/index.html.erb
<% @products.each do |product| %>
    <% if product.category == "Cambodian" %>
        <section class="section">
          <div class="box">
            <article class="product media">
              <figure class="media-left">
                <p class="image is-128x128">
                  <img src="http://placehold.it/256x256">
                </p>
              </figure>
              <div class="media-content">
                <div class="content">
                  <p>
                    <strong><%= product.name %></strong>
                  </p>
                </div>
                <nav class="level">
                  <div class="level-left">
                    <a href="#" data-product-id="<%= product.id %>" class="add-to-cart level-item">
                      <span class="icon"><i class="fa fa-cart-plus"></i></span>
                      Add to Cart
                    </a>
                  </div>
                </nav>
              </div>
            </article>
          </div>
        </section>

    <% end %>
<% end %>

app/views/cart/show.html.erb
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>

<div id="cart">
</div>

<script>
  Stripe.setPublishableKey('pk_test_RNgNHbBV8hZuNpX8LSjS2H2y');

  var cartDiv = document.getElementById('cart');
  var app = Elm.ShoppingCart.embed(cartDiv);

  app.ports.checkout.subscribe(function(card_details) {
    Stripe.card.createToken(card_details, function(status, response) {
      if (response.error) {
        app.ports.cardError.send(response.error.message);
      } else {
        app.ports.cardToken.send(response.id);
      }
    });
  });

  app.ports.updateCount.subscribe(function(count) {
    if(count > 0) {
      $('.nav .cart').text("My Cart (" + count + ")");
    } else {
      $('.nav .cart').text("My Cart");
    }
  });
</script>

app/views/choices/index.html.erb
<div style = "margin-left:50px">
<a href = "/Brazil">Brazil</a><br>
<a href = "/Cambodian">Cambodian</a><br>
<a href = "/Indian">Indian</a><br>
<a href = "/Malaysian">Malaysian</a><br>
<a href = "/MalaysianPlus">Malaysian Plus</a><br>
</div>

app/views/indian/index.html.erb
<% @products.each do |product| %>
    <% if product.category == "Indian" %>
        <section class="section">
          <div class="box">
            <article class="product media">
              <figure class="media-left">
                <p class="image is-128x128">
                  <img src="http://placehold.it/256x256">
                </p>
              </figure>
              <div class="media-content">
                <div class="content">
                  <p>
                    <strong><%= product.name %></strong>
                  </p>
                </div>
                <nav class="level">
                  <div class="level-left">
                    <a href="#" data-product-id="<%= product.id %>" class="add-to-cart level-item">
                      <span class="icon"><i class="fa fa-cart-plus"></i></span>
                      Add to Cart
                    </a>
                  </div>
                </nav>
              </div>
            </article>
          </div>
        </section>

    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hair Obsessionz</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.2.3/css/bulma.min.css">
    <script src="https://use.fontawesome.com/4c58df4ed3.js"></script>
    <%= javascript_include_tag *webpack_asset_paths("application") %>

  </head>

  <body>
    <nav class="nav">
      <div class="nav-left">
        <div class="nav-item">
          <h1 class="title">Hair Obsessionz</h1>
        </div>
      </div>
      <div class="nav-right">
        <div class="nav-item">
          <%= link_to "My Cart", cart_path, class: "cart" %>
          <span class="icon"><i class="fa fa-shopping-cart"></i></span>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/malaysian/index.html.erb
<% @products.each do |product| %>
    <% if product.category == "Malaysian" %>
        <section class="section">
          <div class="box">
            <article class="product media">
              <figure class="media-left">
                <p class="image is-128x128">
                  <img src="http://placehold.it/256x256">
                </p>
              </figure>
              <div class="media-content">
                <div class="content">
                  <p>
                    <strong><%= product.name %></strong>
                  </p>
                </div>
                <nav class="level">
                  <div class="level-left">
                    <a href="#" data-product-id="<%= product.id %>" class="add-to-cart level-item">
                      <span class="icon"><i class="fa fa-cart-plus"></i></span>
                      Add to Cart
                    </a>
                  </div>
                </nav>
              </div>
            </article>
          </div>
        </section>

    <% end %>
<% end %>

app/views/malaysianplus/index.html.erb
<% @products.each do |product| %>
    <% if product.category == "MalaysianPlus" %>
        <section class="section">
          <div class="box">
            <article class="product media">
              <figure class="media-left">
                <p class="image is-128x128">
                  <img src="http://placehold.it/256x256">
                </p>
              </figure>
              <div class="media-content">
                <div class="content">
                  <p>
                    <strong><%= product.name %></strong>
                  </p>
                </div>
                <nav class="level">
                  <div class="level-left">
                    <a href="#" data-product-id="<%= product.id %>" class="add-to-cart level-item">
                      <span class="icon"><i class="fa fa-cart-plus"></i></span>
                      Add to Cart
                    </a>
                  </div>
                </nav>
              </div>
            </article>
          </div>
        </section>

    <% end %>
<% end %>

app/views/products/index.html.erb
<section class="section">
<% @products.each do |product| %>
  <div class="box">
    <article class="product media">
      <figure class="media-left">
        <p class="image is-128x128">
          <img src="http://placehold.it/256x256">
        </p>
      </figure>
      <div class="media-content">
        <div class="content">
          <p>
          <strong><%= product.name %></strong>
          </p>
        </div>
        <nav class="level">
          <div class="level-left">
            <a href="#" data-product-id="<%= product.id %>" class="add-to-cart level-item">
              <span class="icon"><i class="fa fa-cart-plus"></i></span>
              Add to Cart
            </a>
          </div>
        </nav>
      </div>
    </article>
  </div>
<% end %>
</section>

app/views/products/show.html.erb
This particular product